### ISSUE TITLE
question

### ISSUE THREAD

**Issue by CodeWithJosh875** [Elara-Discord-Bots/Elara-Cmdo#7]
are you making another discord bot with the new "Cmdo" you are working on?

i cant see the new one (its in a private resp) but i was just wondering...

**Comment by Elara-Discord-Bots** [comment]
Currently I have no plans on releasing another open sourced Discord bot. 
The most up to date version of "Elara-Cmdo" is [this](https://github.com/elara-bots/Elara-Cmdo-v2) but even that's a little bit outdated by now. 

I plan it put the current up to date version on github soon as the release of v4 of Elara is about to come out(either this month or next month).
 
And sadly due to the Discord changes that's being required the last open sourced bot is [this](https://github.com/elara-bots-archived/PublicBot-Cmdo) but with the Intents being required in the next month that bot will end up not working.

If you have any questions [join the support server](https://superchiefyt.xyz/support)

**Comment by CodeWithJosh875** [comment]
so will (this)[https://github.com/elara-bots-archived/PublicBot-Cmdo] be updated then?

**Comment by Elara-Discord-Bots** [comment]
@contentclue20 sadly no. There is multiple warnings in the repository that say that aswell. 
Due to me trying to maintain the main bot and others I just don't have much time or energy to update that.. or make a new one.

**Comment by CodeWithJosh875** [comment]
can i give a suggestion for Elara v4?

i see this on other open source projects. maybe you can consider adding it to v4

**Comment by CodeWithJosh875** [comment]
not sure if you are doing permission levels or not but a automod module by chance..

**Comment by Elara-Discord-Bots** [comment]
At the moment I don't really plan on adding permission levels (majority of the commands are locked to certain Discord permissions) and in the v4 update commands can be locked per channel (by putting `[-command_name]` and/or `[admin]` or `[mod]`, which would lock that command and any other commands included to that permission) as for the automod currently no, right now I have a public bot created to handle automod 
Docs/Website: https://mod.superchiefyt.xyz  
Invite: https://mod.superchiefyt.xyz/invite

**Comment by Elara-Discord-Bots** [comment]
Anyways, if you have any more suggestions or feedback join the support server above^
